version: '3.8'

services:

  elasticsearch:
    build:
      context: ./elk/elasticsearch/files
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - XPACK_SECURITY_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elk/elasticsearch/files/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - esdata1:/usr/share/elasticsearch/data:z
    ports:
      - 9200:9200
    networks:
      - elk

  logstash:
    build:
      context: ./elk/logstash/files
    container_name: logstash
    volumes:
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5046:5046
    environment:
      - "LS_JAVA_OPTS= -Xms256m -Xmx256m"
      - XPACK_SECURITY_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    build:
      context: ./elk/kibana/files
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    volumes:
      - ./elk/kibana/files/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z  
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  esdata1:
    driver: local

networks:
  elk:
    driver: bridge
