---
- name: Install Nginx Web Server 
  apt:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: nginx }
    - { name: apache2-utils}
  notify: nginx systemd

- name: Copy Kibana Nginx conf
  copy: 
    src: nginx/files/default
    dest: /etc/nginx/sites-available/default

- name: Allow HTTP iptables
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
    comment: Accept new HTTP connections.

- name: Add a user to a password file and ensure permissions are set
  community.general.htpasswd:
    path: /etc/nginx/.kibana-user
    name: elastic
    password: 'changeme'
    owner: root
    group: root
    mode: 0640
