---
- name: Install Nginx Web Server 
  apt:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: nginx }
    - { name: apache2-utils}

- name: Install certain python modules for nginx
  pip:
    name: "{{ item.name }}"
    state: present
  with_items:
  - { name: passlib}
      
- name: Copy Kibana Nginx conf
  copy: 
    src: nginx/files/default
    dest: /etc/nginx/sites-available/default

- name: Allow HTTP iptables
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
    comment: Accept new HTTP connections.

- name: Add a user to a password file and ensure permissions are set
  htpasswd:
    path: /etc/nginx/.kibana-user
    name: "{{ htpasswd_user }} "
    password: "{{ htpasswd_password }}"
    owner: root
    group: www-data
    mode: 0640
  notify: nginx systemd  
