---
- name: Copy Docker-Compose files
  copy:
    src: ./{{ item }}
    dest: ./go-grab-log{{ item }}
  loop:
  - docker-compose.yml
  - elk

# Docker_compose ansible module is required!
- name: Deploy Docker-Compose stack
  docker_compose:
    project_src: ./go-grab-log
    files:
    - docker-compose.yml
  vars:
    ansible_python_interpreter: /bin/python3    
