---
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
docker_repo_url: https://download.docker.com/linux

docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

docker_apt_release_channel: stable
docker_apt_repository: "deb {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true
docker_apt_gpg_key: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg"

